/*----------------------------------------------------------------*/
/* */
/* SEMAPHORE constant and type definitions and management services*/
/* */
/*----------------------------------------------------------------*/
#ifndef APEX_SEMAPHORE
#define APEX_SEMAPHORE

#ifdef __cplusplus
extern "C" {
#endif

#include "apex_types.h"

#define MAX_NUMBER_OF_SEMAPHORES SYSTEM_LIMIT_NUMBER_OF_SEMAPHORES
#define MAX_SEMAPHORE_VALUE 32767
typedef NAME_TYPE SEMAPHORE_NAME_TYPE;
typedef APEX_INTEGER SEMAPHORE_ID_TYPE;
typedef APEX_INTEGER SEMAPHORE_VALUE_TYPE;
typedef
struct {
  SEMAPHORE_VALUE_TYPE CURRENT_VALUE;
  SEMAPHORE_VALUE_TYPE MAXIMUM_VALUE;
  WAITING_RANGE_TYPE WAITING_PROCESSES;
} SEMAPHORE_STATUS_TYPE;
#define CREATE_SEMAPHORE(SEMAPHORE_NAME, CURRENT_VALUE, MAXIMUM_VALUE, QUEUING_DISCIPLINE, SEMAPHORE_ID, RETURN_CODE) JL653_CREATE_SEMAPHORE(__FILE__, __FUNCTION__, __LINE__, SEMAPHORE_NAME, CURRENT_VALUE, MAXIMUM_VALUE, QUEUING_DISCIPLINE, SEMAPHORE_ID, RETURN_CODE)
JL653SHELL_API void JL653_CREATE_SEMAPHORE (
  const char *location_file,
  const char *location_function,
  int location_line,
  /*in */ SEMAPHORE_NAME_TYPE SEMAPHORE_NAME,
  /*in */ SEMAPHORE_VALUE_TYPE CURRENT_VALUE,
  /*in */ SEMAPHORE_VALUE_TYPE MAXIMUM_VALUE,
  /*in */ QUEUING_DISCIPLINE_TYPE QUEUING_DISCIPLINE,
  /*out*/ SEMAPHORE_ID_TYPE *SEMAPHORE_ID,
  /*out*/ RETURN_CODE_TYPE *RETURN_CODE );
#define WAIT_SEMAPHORE(SEMAPHORE_ID, TIME_OUT, RETURN_CODE) JL653_WAIT_SEMAPHORE(__FILE__, __FUNCTION__, __LINE__, SEMAPHORE_ID, TIME_OUT, RETURN_CODE)
JL653SHELL_API void JL653_WAIT_SEMAPHORE (
  const char *location_file,
  const char *location_function,
  int location_line,
  /*in */ SEMAPHORE_ID_TYPE SEMAPHORE_ID,
  /*in */ SYSTEM_TIME_TYPE TIME_OUT,
  /*out*/ RETURN_CODE_TYPE *RETURN_CODE );
#define SIGNAL_SEMAPHORE(SEMAPHORE_ID, RETURN_CODE) JL653_SIGNAL_SEMAPHORE(__FILE__, __FUNCTION__, __LINE__, SEMAPHORE_ID, RETURN_CODE)
JL653SHELL_API void JL653_SIGNAL_SEMAPHORE (
  const char *location_file,
  const char *location_function,
  int location_line,
  /*in */ SEMAPHORE_ID_TYPE SEMAPHORE_ID,
  /*out*/ RETURN_CODE_TYPE *RETURN_CODE );
#define GET_SEMAPHORE_ID(SEMAPHORE_NAME, SEMAPHORE_ID, RETURN_CODE) JL653_GET_SEMAPHORE_ID(__FILE__, __FUNCTION__, __LINE__, SEMAPHORE_NAME, SEMAPHORE_ID, RETURN_CODE)
JL653SHELL_API void JL653_GET_SEMAPHORE_ID (
  const char *location_file,
  const char *location_function,
  int location_line,
  /*in */ SEMAPHORE_NAME_TYPE SEMAPHORE_NAME,
  /*out*/ SEMAPHORE_ID_TYPE *SEMAPHORE_ID,
  /*out*/ RETURN_CODE_TYPE *RETURN_CODE );
#define GET_SEMAPHORE_STATUS(SEMAPHORE_ID, SEMAPHORE_STATUS, RETURN_CODE) JL653_GET_SEMAPHORE_STATUS(__FILE__, __FUNCTION__, __LINE__, SEMAPHORE_ID, SEMAPHORE_STATUS, RETURN_CODE)
JL653SHELL_API void JL653_GET_SEMAPHORE_STATUS (
  const char *location_file,
  const char *location_function,
  int location_line,
  /*in */ SEMAPHORE_ID_TYPE SEMAPHORE_ID,
  /*out*/ SEMAPHORE_STATUS_TYPE *SEMAPHORE_STATUS,
  /*out*/ RETURN_CODE_TYPE *RETURN_CODE );

#ifdef __cplusplus
}
#endif

#endif